FROM php:8.2-cli

RUN docker-php-ext-install pdo_mysql mysqli

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libicu-dev \
    && docker-php-ext-install bcmath intl

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app
COPY . .

RUN composer install --no-dev --optimize-autoloader --no-interaction

EXPOSE 8080
CMD php artisan serve --host=0.0.0.0 --port=$PORT

